#define IDD_MAIN                        101

#define IDC_COMBO_PROVTYPE              1001
#define IDC_COMBO_PROVNAME              1002
#define IDC_BTN_SEARCH_USER             1003
#define IDC_BTN_SEARCH_MACHINE          1004
#define IDC_LIST_CONTAINERS             1005
#define IDC_EDIT_CONTAINERNAME          1006
#define IDC_RADIO_EXCHANGE              1007
#define IDC_RADIO_SIGNATURE             1008
#define IDC_EDIT_KEY_EXCHG_PUB          1009
#define IDC_EDIT_KEY_EXCHG_PRI          1010
#define IDC_EDIT_KEY_SIG_PUB            1011
#define IDC_EDIT_KEY_SIG_PRI            1012
#define IDC_BTN_SAVE_EXCHG_PUB          1013
#define IDC_BTN_SAVE_EXCHG_PRI          1014
#define IDC_BTN_SAVE_SIG_PUB            1015
#define IDC_BTN_SAVE_SIG_PRI            1016
#define IDC_COMBO_HASH                  1017
#define IDC_COMBO_HASH_FORMAT           1018
#define IDC_EDIT_HASH                   1019
#define IDC_EDIT_SIGNATURE              1020
#define IDC_BTN_SIGN                    1021
#define IDC_CHECK_FLIP                  1022
#define IDC_COMBO_SIGNATURE_FORMAT      1023
